using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("CFT & ACM")]
[assembly: AssemblyVersionAttribute("0.8.0.0")]
[assembly: AssemblyFileVersionAttribute("0.8.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.8.0.0")]
[assembly: AssemblyTitleAttribute("Topshelf")]
[assembly: AssemblyProductAttribute("Topshelf")]
[assembly: AssemblyDescriptionAttribute("Topshelf is a product of CFT & ACM")]
[assembly: AssemblyTrademarkAttribute("Topshelf - CFT & ACM")]
[assembly: AssemblyCopyrightAttribute("Copyright 2012 CFT & ACM, - Original author or authors")]

